version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
      MYSQL_USER: crmuser
      MYSQL_PASSWORD: crmpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  node:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173"

volumes:
  db_data:
